Replace setup.py with pyproject.toml
The former is deprecated and mypy would complain:

    error: Skipping analyzing "setuptools": module is installed, but missing library stubs or py.typed marker

`pyproject.toml` is also significantly cleaner.

https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
https://packaging.python.org/en/latest/guides/single-sourcing-package-version/
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html